### PR TITLE
Linking view

### PR DESCRIPTION
**Pull request by hypesystem**

### CODE REVIEW

**Comment by hypesystem** [comment]
WIP, current state: 
image

**Comment by hypesystem** [comment]
I think this might be a good enough v1? (Still need to clean up code.)

image
image

**Comment by Arth101** [comment]
Saw this on my computer. Two link description circles?
image

**Comment by Arth101** [comment]
The static height can cause some problems (as we expected):
image

**Comment by Arth101** [comment]
I dont think we should use the static height on source cards in the search result list.
image

**Review by Arth101 — CHANGES_REQUESTED** [review]
Wow, that looks super good! Well done :). Graceful.
There is some visual bugs that I've postet screenshots of, and I think we should only use the static height for the source-cards on the Lifecourse page, to avoid a lot of overflowing issues in the future. Otherwise we could make it a `min-height`?

**Comment by hypesystem** [comment]
It has to be a fixed height for the svg to align, unfortunately :frowning:

I have made a few adjustments and moved fixed height to be only on lifecourse page. Please re-review :smile:

**Pull request merged**
